# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :tests do
      run_tests(scheme: "iOS")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    if is_ci
      # xcversion(version: "~> 12.4.0")
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    match(
      type: "appstore",
      app_identifier:["com.app.oluko.qa","com.app.oluko.qa.ImageNoti"],
      readonly: is_ci,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )
    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",
    export_method: "app-store", xcargs: "-allowProvisioningUpdates")
    # firebase_app_distribution(
    #         app: "1:14784345427:ios:e3aa4c755c3d4138131da6",
    #     )
    upload_to_testflight(changelog: "🚀", distribute_external:true, groups:"Beta Testers")
  end
end
