# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
ENV['SUPPLY_UPLOAD_MAX_RETRIES']='5'

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh "cd .. && cd .. && bash ./scripts.sh increment_build"
    # gradle(task: "clean")
    sh "cd .. && cd .. && bash ./scripts.sh appbundle"
    # crashlytics
    upload_to_play_store(track:"internal", 
    aab: "../build/app/outputs/bundle/release/app-release.aab", 
    rollout: "1")
    upload_to_play_store(track:"internal",track_promote_to:"alpha", skip_upload_aab:true, skip_upload_apk:true,
    skip_upload_metadata:true,skip_upload_changelogs:true)
    # OPEN TESTING PROMOTION
    upload_to_play_store(track:"alpha",track_promote_to:"beta", skip_upload_aab:true, skip_upload_apk:true,
    skip_upload_metadata:true,skip_upload_changelogs:true)
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
